/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : bigint,
  'status' : string,
  'content' : string,
}
export interface DailyLogEntry {
  'id' : bigint,
  'startTime' : TimeOfDay,
  'activityName' : string,
  'supervisors' : bigint,
  'totalPauseDuration' : number,
  'plannedQuantity' : number,
  'endTime' : TimeOfDay,
  'date' : Timestamp,
  'laborers' : bigint,
  'unit' : string,
  'submittedAt' : Timestamp,
  'submittedBy' : Principal,
  'interruptions' : Array<Interruption>,
  'photoIds' : Array<string>,
  'projectId' : bigint,
  'totalWorkingHours' : number,
  'netWorkingHours' : number,
  'actualQuantity' : number,
  'remarks' : string,
}
export interface DashboardMetrics {
  'totalProjects' : bigint,
  'overallProgress' : number,
  'totalInterruptionsThisWeek' : bigint,
  'logStatus' : { 'pending' : bigint, 'completed' : boolean },
  'totalWorkingDays' : bigint,
}
export interface DelayInstance {
  'duration' : bigint,
  'timestamp' : Timestamp,
  'reason' : string,
}
export interface Interruption {
  'startTime' : TimeOfDay,
  'duration' : number,
  'endTime' : TimeOfDay,
  'reason' : string,
}
export interface PlannedTarget {
  'activityName' : string,
  'endDate' : Timestamp,
  'plannedDailyQuantity' : number,
  'unit' : string,
  'startDate' : Timestamp,
}
export interface Project {
  'id' : bigint,
  'status' : string,
  'plannedWorkingHoursPerDay' : number,
  'projectType' : ProjectType,
  'owner' : Principal,
  'name' : string,
  'createdAt' : Timestamp,
  'workingDaysPerWeek' : bigint,
  'plannedCompletionDate' : Timestamp,
  'weeklyLogs' : Array<WeeklyLog>,
  'comments' : Array<Comment>,
  'assignedUsers' : Array<Principal>,
  'location' : string,
  'startDate' : Timestamp,
}
export type ProjectType = { 'commercial' : null } |
  { 'infrastructure' : null } |
  { 'residential' : null } |
  { 'industrial' : null };
export type StandardizedRole = { 'admin' : null } |
  { 'site_engineer' : null } |
  { 'project_manager' : null };
export type TimeOfDay = string;
export type Timestamp = bigint;
export interface UserProfile {
  'assignedProject' : [] | [bigint],
  'designation' : string,
  'role' : StandardizedRole,
  'fullName' : string,
  'companyName' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeeklyLog {
  'id' : bigint,
  'status' : string,
  'content' : string,
}
export interface WeeklySummary {
  'delayRisks' : Array<string>,
  'plannedQuantity' : number,
  'achievedProductivity' : number,
  'plannedProductivity' : number,
  'projectId' : bigint,
  'achievedQuantity' : number,
  'delayInstances' : Array<DelayInstance>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRole' : ActorMethod<[Principal, StandardizedRole], undefined>,
  'assignUserToProject' : ActorMethod<[bigint, Principal], undefined>,
  'calculateDelay' : ActorMethod<[bigint], Array<[bigint, bigint]>>,
  'createProject' : ActorMethod<
    [string, string, ProjectType, Timestamp, Timestamp, number, bigint],
    bigint
  >,
  'getAchievements' : ActorMethod<[], Array<string>>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChallenges' : ActorMethod<[string], Array<string>>,
  'getDailyLogsByProject' : ActorMethod<[bigint], Array<DailyLogEntry>>,
  'getDashboardMetrics' : ActorMethod<[], DashboardMetrics>,
  'getEfficiency' : ActorMethod<[string], Array<string>>,
  'getInterval' : ActorMethod<[], string>,
  'getPlannedTargets' : ActorMethod<[bigint], Array<PlannedTarget>>,
  'getProject' : ActorMethod<[bigint], Project>,
  'getTasks' : ActorMethod<[], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRole' : ActorMethod<[Principal], StandardizedRole>,
  'getWeeklySummary' : ActorMethod<[bigint], WeeklySummary>,
  'getWorkforceData' : ActorMethod<[], Array<string>>,
  'initializeAccessControl' : ActorMethod<[string, string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isUserRole' : ActorMethod<[Principal, StandardizedRole], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setPlannedTargets' : ActorMethod<[bigint, Array<PlannedTarget>], undefined>,
  'submitDailyLog' : ActorMethod<
    [
      bigint,
      string,
      number,
      number,
      string,
      bigint,
      bigint,
      TimeOfDay,
      TimeOfDay,
      number,
      Array<Interruption>,
      Array<string>,
      string,
    ],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];