/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StandardizedRole = IDL.Variant({
  'admin' : IDL.Null,
  'site_engineer' : IDL.Null,
  'project_manager' : IDL.Null,
});
export const ProjectType = IDL.Variant({
  'commercial' : IDL.Null,
  'infrastructure' : IDL.Null,
  'residential' : IDL.Null,
  'industrial' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const WeeklyLog = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'content' : IDL.Text,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'content' : IDL.Text,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'plannedWorkingHoursPerDay' : IDL.Float64,
  'projectType' : ProjectType,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'workingDaysPerWeek' : IDL.Nat,
  'plannedCompletionDate' : Timestamp,
  'weeklyLogs' : IDL.Vec(WeeklyLog),
  'comments' : IDL.Vec(Comment),
  'assignedUsers' : IDL.Vec(IDL.Principal),
  'location' : IDL.Text,
  'startDate' : Timestamp,
});
export const UserProfile = IDL.Record({
  'assignedProject' : IDL.Opt(IDL.Nat),
  'designation' : IDL.Text,
  'role' : StandardizedRole,
  'fullName' : IDL.Text,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
});
export const TimeOfDay = IDL.Text;
export const Interruption = IDL.Record({
  'startTime' : TimeOfDay,
  'duration' : IDL.Float64,
  'endTime' : TimeOfDay,
  'reason' : IDL.Text,
});
export const DailyLogEntry = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : TimeOfDay,
  'activityName' : IDL.Text,
  'supervisors' : IDL.Nat,
  'totalPauseDuration' : IDL.Float64,
  'plannedQuantity' : IDL.Float64,
  'endTime' : TimeOfDay,
  'date' : Timestamp,
  'laborers' : IDL.Nat,
  'unit' : IDL.Text,
  'submittedAt' : Timestamp,
  'submittedBy' : IDL.Principal,
  'interruptions' : IDL.Vec(Interruption),
  'photoIds' : IDL.Vec(IDL.Text),
  'projectId' : IDL.Nat,
  'totalWorkingHours' : IDL.Float64,
  'netWorkingHours' : IDL.Float64,
  'actualQuantity' : IDL.Float64,
  'remarks' : IDL.Text,
});
export const DashboardMetrics = IDL.Record({
  'totalProjects' : IDL.Nat,
  'overallProgress' : IDL.Float64,
  'totalInterruptionsThisWeek' : IDL.Nat,
  'logStatus' : IDL.Record({ 'pending' : IDL.Nat, 'completed' : IDL.Bool }),
  'totalWorkingDays' : IDL.Nat,
});
export const PlannedTarget = IDL.Record({
  'activityName' : IDL.Text,
  'endDate' : Timestamp,
  'plannedDailyQuantity' : IDL.Float64,
  'unit' : IDL.Text,
  'startDate' : Timestamp,
});
export const DelayInstance = IDL.Record({
  'duration' : IDL.Nat,
  'timestamp' : Timestamp,
  'reason' : IDL.Text,
});
export const WeeklySummary = IDL.Record({
  'delayRisks' : IDL.Vec(IDL.Text),
  'plannedQuantity' : IDL.Float64,
  'achievedProductivity' : IDL.Float64,
  'plannedProductivity' : IDL.Float64,
  'projectId' : IDL.Nat,
  'achievedQuantity' : IDL.Float64,
  'delayInstances' : IDL.Vec(DelayInstance),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignRole' : IDL.Func([IDL.Principal, StandardizedRole], [], []),
  'assignUserToProject' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'calculateDelay' : IDL.Func(
      [IDL.Int],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Int))],
      ['query'],
    ),
  'createProject' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        ProjectType,
        Timestamp,
        Timestamp,
        IDL.Float64,
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
  'getAchievements' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChallenges' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getDailyLogsByProject' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(DailyLogEntry)],
      ['query'],
    ),
  'getDashboardMetrics' : IDL.Func([], [DashboardMetrics], ['query']),
  'getEfficiency' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getInterval' : IDL.Func([], [IDL.Text], ['query']),
  'getPlannedTargets' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(PlannedTarget)],
      ['query'],
    ),
  'getProject' : IDL.Func([IDL.Nat], [Project], ['query']),
  'getTasks' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRole' : IDL.Func([IDL.Principal], [StandardizedRole], ['query']),
  'getWeeklySummary' : IDL.Func([IDL.Nat], [WeeklySummary], ['query']),
  'getWorkforceData' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'initializeAccessControl' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserRole' : IDL.Func(
      [IDL.Principal, StandardizedRole],
      [IDL.Bool],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setPlannedTargets' : IDL.Func([IDL.Nat, IDL.Vec(PlannedTarget)], [], []),
  'submitDailyLog' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        TimeOfDay,
        TimeOfDay,
        IDL.Float64,
        IDL.Vec(Interruption),
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StandardizedRole = IDL.Variant({
    'admin' : IDL.Null,
    'site_engineer' : IDL.Null,
    'project_manager' : IDL.Null,
  });
  const ProjectType = IDL.Variant({
    'commercial' : IDL.Null,
    'infrastructure' : IDL.Null,
    'residential' : IDL.Null,
    'industrial' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const WeeklyLog = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'content' : IDL.Text,
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'content' : IDL.Text,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'plannedWorkingHoursPerDay' : IDL.Float64,
    'projectType' : ProjectType,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'workingDaysPerWeek' : IDL.Nat,
    'plannedCompletionDate' : Timestamp,
    'weeklyLogs' : IDL.Vec(WeeklyLog),
    'comments' : IDL.Vec(Comment),
    'assignedUsers' : IDL.Vec(IDL.Principal),
    'location' : IDL.Text,
    'startDate' : Timestamp,
  });
  const UserProfile = IDL.Record({
    'assignedProject' : IDL.Opt(IDL.Nat),
    'designation' : IDL.Text,
    'role' : StandardizedRole,
    'fullName' : IDL.Text,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const TimeOfDay = IDL.Text;
  const Interruption = IDL.Record({
    'startTime' : TimeOfDay,
    'duration' : IDL.Float64,
    'endTime' : TimeOfDay,
    'reason' : IDL.Text,
  });
  const DailyLogEntry = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : TimeOfDay,
    'activityName' : IDL.Text,
    'supervisors' : IDL.Nat,
    'totalPauseDuration' : IDL.Float64,
    'plannedQuantity' : IDL.Float64,
    'endTime' : TimeOfDay,
    'date' : Timestamp,
    'laborers' : IDL.Nat,
    'unit' : IDL.Text,
    'submittedAt' : Timestamp,
    'submittedBy' : IDL.Principal,
    'interruptions' : IDL.Vec(Interruption),
    'photoIds' : IDL.Vec(IDL.Text),
    'projectId' : IDL.Nat,
    'totalWorkingHours' : IDL.Float64,
    'netWorkingHours' : IDL.Float64,
    'actualQuantity' : IDL.Float64,
    'remarks' : IDL.Text,
  });
  const DashboardMetrics = IDL.Record({
    'totalProjects' : IDL.Nat,
    'overallProgress' : IDL.Float64,
    'totalInterruptionsThisWeek' : IDL.Nat,
    'logStatus' : IDL.Record({ 'pending' : IDL.Nat, 'completed' : IDL.Bool }),
    'totalWorkingDays' : IDL.Nat,
  });
  const PlannedTarget = IDL.Record({
    'activityName' : IDL.Text,
    'endDate' : Timestamp,
    'plannedDailyQuantity' : IDL.Float64,
    'unit' : IDL.Text,
    'startDate' : Timestamp,
  });
  const DelayInstance = IDL.Record({
    'duration' : IDL.Nat,
    'timestamp' : Timestamp,
    'reason' : IDL.Text,
  });
  const WeeklySummary = IDL.Record({
    'delayRisks' : IDL.Vec(IDL.Text),
    'plannedQuantity' : IDL.Float64,
    'achievedProductivity' : IDL.Float64,
    'plannedProductivity' : IDL.Float64,
    'projectId' : IDL.Nat,
    'achievedQuantity' : IDL.Float64,
    'delayInstances' : IDL.Vec(DelayInstance),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignRole' : IDL.Func([IDL.Principal, StandardizedRole], [], []),
    'assignUserToProject' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'calculateDelay' : IDL.Func(
        [IDL.Int],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Int))],
        ['query'],
      ),
    'createProject' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ProjectType,
          Timestamp,
          Timestamp,
          IDL.Float64,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'getAchievements' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChallenges' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getDailyLogsByProject' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(DailyLogEntry)],
        ['query'],
      ),
    'getDashboardMetrics' : IDL.Func([], [DashboardMetrics], ['query']),
    'getEfficiency' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getInterval' : IDL.Func([], [IDL.Text], ['query']),
    'getPlannedTargets' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(PlannedTarget)],
        ['query'],
      ),
    'getProject' : IDL.Func([IDL.Nat], [Project], ['query']),
    'getTasks' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRole' : IDL.Func([IDL.Principal], [StandardizedRole], ['query']),
    'getWeeklySummary' : IDL.Func([IDL.Nat], [WeeklySummary], ['query']),
    'getWorkforceData' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'initializeAccessControl' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserRole' : IDL.Func(
        [IDL.Principal, StandardizedRole],
        [IDL.Bool],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setPlannedTargets' : IDL.Func([IDL.Nat, IDL.Vec(PlannedTarget)], [], []),
    'submitDailyLog' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          TimeOfDay,
          TimeOfDay,
          IDL.Float64,
          IDL.Vec(Interruption),
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };