/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface WeeklyLog {
    id: bigint;
    status: string;
    content: string;
}
export interface Comment {
    id: bigint;
    status: string;
    content: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Interruption {
    startTime: TimeOfDay;
    duration: number;
    endTime: TimeOfDay;
    reason: string;
}
export interface DailyLogEntry {
    id: bigint;
    startTime: TimeOfDay;
    activityName: string;
    supervisors: bigint;
    totalPauseDuration: number;
    plannedQuantity: number;
    endTime: TimeOfDay;
    date: Timestamp;
    laborers: bigint;
    unit: string;
    submittedAt: Timestamp;
    submittedBy: Principal;
    interruptions: Array<Interruption>;
    photoIds: Array<string>;
    projectId: bigint;
    totalWorkingHours: number;
    netWorkingHours: number;
    actualQuantity: number;
    remarks: string;
}
export interface WeeklySummary {
    delayRisks: Array<string>;
    plannedQuantity: number;
    achievedProductivity: number;
    plannedProductivity: number;
    projectId: bigint;
    achievedQuantity: number;
    delayInstances: Array<DelayInstance>;
}
export interface DelayInstance {
    duration: bigint;
    timestamp: Timestamp;
    reason: string;
}
export type TimeOfDay = string;
export interface PlannedTarget {
    activityName: string;
    endDate: Timestamp;
    plannedDailyQuantity: number;
    unit: string;
    startDate: Timestamp;
}
export interface DashboardMetrics {
    totalProjects: bigint;
    overallProgress: number;
    totalInterruptionsThisWeek: bigint;
    logStatus: {
        pending: bigint;
        completed: boolean;
    };
    totalWorkingDays: bigint;
}
export interface Project {
    id: bigint;
    status: string;
    plannedWorkingHoursPerDay: number;
    projectType: ProjectType;
    owner: Principal;
    name: string;
    createdAt: Timestamp;
    workingDaysPerWeek: bigint;
    plannedCompletionDate: Timestamp;
    weeklyLogs: Array<WeeklyLog>;
    comments: Array<Comment>;
    assignedUsers: Array<Principal>;
    location: string;
    startDate: Timestamp;
}
export interface UserProfile {
    assignedProject?: bigint;
    designation: string;
    role: StandardizedRole;
    fullName: string;
    companyName: string;
    phone: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ProjectType {
    commercial = "commercial",
    infrastructure = "infrastructure",
    residential = "residential",
    industrial = "industrial"
}
export enum StandardizedRole {
    admin = "admin",
    site_engineer = "site_engineer",
    project_manager = "project_manager"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignRole(user: Principal, role: StandardizedRole): Promise<void>;
    assignUserToProject(projectId: bigint, user: Principal): Promise<void>;
    calculateDelay(arg0: bigint): Promise<Array<[bigint, bigint]>>;
    createProject(name: string, location: string, projectType: ProjectType, startDate: Timestamp, plannedCompletionDate: Timestamp, plannedWorkingHoursPerDay: number, workingDaysPerWeek: bigint): Promise<bigint>;
    getAchievements(): Promise<Array<string>>;
    getAllProjects(): Promise<Array<Project>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChallenges(arg0: string): Promise<Array<string>>;
    getDailyLogsByProject(projectId: bigint): Promise<Array<DailyLogEntry>>;
    getDashboardMetrics(): Promise<DashboardMetrics>;
    getEfficiency(arg0: string): Promise<Array<string>>;
    getInterval(): Promise<string>;
    getPlannedTargets(projectId: bigint): Promise<Array<PlannedTarget>>;
    getProject(id: bigint): Promise<Project>;
    getTasks(): Promise<Array<string>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserRole(user: Principal): Promise<StandardizedRole>;
    getWeeklySummary(projectId: bigint): Promise<WeeklySummary>;
    getWorkforceData(): Promise<Array<string>>;
    initializeAccessControl(adminToken: string, userProvidedToken: string): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isUserRole(user: Principal, role: StandardizedRole): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setPlannedTargets(projectId: bigint, targets: Array<PlannedTarget>): Promise<void>;
    submitDailyLog(projectId: bigint, activityName: string, plannedQuantity: number, actualQuantity: number, unit: string, laborers: bigint, supervisors: bigint, startTime: TimeOfDay, endTime: TimeOfDay, totalWorkingHours: number, interruptions: Array<Interruption>, photoIds: Array<string>, remarks: string): Promise<bigint>;
}
import type { Comment as _Comment, Project as _Project, ProjectType as _ProjectType, StandardizedRole as _StandardizedRole, Timestamp as _Timestamp, UserProfile as _UserProfile, UserRole as _UserRole, WeeklyLog as _WeeklyLog, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignRole(arg0: Principal, arg1: StandardizedRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRole(arg0, to_candid_StandardizedRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRole(arg0, to_candid_StandardizedRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignUserToProject(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignUserToProject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignUserToProject(arg0, arg1);
            return result;
        }
    }
    async calculateDelay(arg0: bigint): Promise<Array<[bigint, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateDelay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateDelay(arg0);
            return result;
        }
    }
    async createProject(arg0: string, arg1: string, arg2: ProjectType, arg3: Timestamp, arg4: Timestamp, arg5: number, arg6: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0, arg1, to_candid_ProjectType_n12(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0, arg1, to_candid_ProjectType_n12(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async getAchievements(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAchievements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAchievements();
            return result;
        }
    }
    async getAllProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjects();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjects();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChallenges(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChallenges(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChallenges(arg0);
            return result;
        }
    }
    async getDailyLogsByProject(arg0: bigint): Promise<Array<DailyLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyLogsByProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyLogsByProject(arg0);
            return result;
        }
    }
    async getDashboardMetrics(): Promise<DashboardMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardMetrics();
            return result;
        }
    }
    async getEfficiency(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEfficiency(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEfficiency(arg0);
            return result;
        }
    }
    async getInterval(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getInterval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInterval();
            return result;
        }
    }
    async getPlannedTargets(arg0: bigint): Promise<Array<PlannedTarget>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlannedTargets(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlannedTargets(arg0);
            return result;
        }
    }
    async getProject(arg0: bigint): Promise<Project> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_Project_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_Project_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasks(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasks();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserRole(arg0: Principal): Promise<StandardizedRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRole(arg0);
                return from_candid_StandardizedRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRole(arg0);
            return from_candid_StandardizedRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeeklySummary(arg0: bigint): Promise<WeeklySummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklySummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklySummary(arg0);
            return result;
        }
    }
    async getWorkforceData(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkforceData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkforceData();
            return result;
        }
    }
    async initializeAccessControl(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl(arg0, arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isUserRole(arg0: Principal, arg1: StandardizedRole): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUserRole(arg0, to_candid_StandardizedRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUserRole(arg0, to_candid_StandardizedRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n26(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n26(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setPlannedTargets(arg0: bigint, arg1: Array<PlannedTarget>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPlannedTargets(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPlannedTargets(arg0, arg1);
            return result;
        }
    }
    async submitDailyLog(arg0: bigint, arg1: string, arg2: number, arg3: number, arg4: string, arg5: bigint, arg6: bigint, arg7: TimeOfDay, arg8: TimeOfDay, arg9: number, arg10: Array<Interruption>, arg11: Array<string>, arg12: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitDailyLog(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitDailyLog(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
            return result;
        }
    }
}
function from_candid_ProjectType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectType): ProjectType {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_StandardizedRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StandardizedRole): StandardizedRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    plannedWorkingHoursPerDay: number;
    projectType: _ProjectType;
    owner: Principal;
    name: string;
    createdAt: _Timestamp;
    workingDaysPerWeek: bigint;
    plannedCompletionDate: _Timestamp;
    weeklyLogs: Array<_WeeklyLog>;
    comments: Array<_Comment>;
    assignedUsers: Array<Principal>;
    location: string;
    startDate: _Timestamp;
}): {
    id: bigint;
    status: string;
    plannedWorkingHoursPerDay: number;
    projectType: ProjectType;
    owner: Principal;
    name: string;
    createdAt: Timestamp;
    workingDaysPerWeek: bigint;
    plannedCompletionDate: Timestamp;
    weeklyLogs: Array<WeeklyLog>;
    comments: Array<Comment>;
    assignedUsers: Array<Principal>;
    location: string;
    startDate: Timestamp;
} {
    return {
        id: value.id,
        status: value.status,
        plannedWorkingHoursPerDay: value.plannedWorkingHoursPerDay,
        projectType: from_candid_ProjectType_n17(_uploadFile, _downloadFile, value.projectType),
        owner: value.owner,
        name: value.name,
        createdAt: value.createdAt,
        workingDaysPerWeek: value.workingDaysPerWeek,
        plannedCompletionDate: value.plannedCompletionDate,
        weeklyLogs: value.weeklyLogs,
        comments: value.comments,
        assignedUsers: value.assignedUsers,
        location: value.location,
        startDate: value.startDate
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assignedProject: [] | [bigint];
    designation: string;
    role: _StandardizedRole;
    fullName: string;
    companyName: string;
    phone: string;
}): {
    assignedProject?: bigint;
    designation: string;
    role: StandardizedRole;
    fullName: string;
    companyName: string;
    phone: string;
} {
    return {
        assignedProject: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.assignedProject)),
        designation: value.designation,
        role: from_candid_StandardizedRole_n22(_uploadFile, _downloadFile, value.role),
        fullName: value.fullName,
        companyName: value.companyName,
        phone: value.phone
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    commercial: null;
} | {
    infrastructure: null;
} | {
    residential: null;
} | {
    industrial: null;
}): ProjectType {
    return "commercial" in value ? ProjectType.commercial : "infrastructure" in value ? ProjectType.infrastructure : "residential" in value ? ProjectType.residential : "industrial" in value ? ProjectType.industrial : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    site_engineer: null;
} | {
    project_manager: null;
}): StandardizedRole {
    return "admin" in value ? StandardizedRole.admin : "site_engineer" in value ? StandardizedRole.site_engineer : "project_manager" in value ? StandardizedRole.project_manager : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n15(_uploadFile, _downloadFile, x));
}
function to_candid_ProjectType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectType): _ProjectType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_StandardizedRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StandardizedRole): _StandardizedRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assignedProject?: bigint;
    designation: string;
    role: StandardizedRole;
    fullName: string;
    companyName: string;
    phone: string;
}): {
    assignedProject: [] | [bigint];
    designation: string;
    role: _StandardizedRole;
    fullName: string;
    companyName: string;
    phone: string;
} {
    return {
        assignedProject: value.assignedProject ? candid_some(value.assignedProject) : candid_none(),
        designation: value.designation,
        role: to_candid_StandardizedRole_n10(_uploadFile, _downloadFile, value.role),
        fullName: value.fullName,
        companyName: value.companyName,
        phone: value.phone
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StandardizedRole): {
    admin: null;
} | {
    site_engineer: null;
} | {
    project_manager: null;
} {
    return value == StandardizedRole.admin ? {
        admin: null
    } : value == StandardizedRole.site_engineer ? {
        site_engineer: null
    } : value == StandardizedRole.project_manager ? {
        project_manager: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectType): {
    commercial: null;
} | {
    infrastructure: null;
} | {
    residential: null;
} | {
    industrial: null;
} {
    return value == ProjectType.commercial ? {
        commercial: null
    } : value == ProjectType.infrastructure ? {
        infrastructure: null
    } : value == ProjectType.residential ? {
        residential: null
    } : value == ProjectType.industrial ? {
        industrial: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
